/** FIFA team name → ISO 3166-1 alpha-2 (or subdivision slug for flagcdn) */
const TEAM_COUNTRY_CODE: Record<string, string> = {
  Algeria: 'DZ',
  Argentina: 'AR',
  Australia: 'AU',
  AUS: 'AU',
  Austria: 'AT',
  Belgium: 'BE',
  BEL: 'BE',
  'Bosnia & Herzegovina': 'BA',
  BIH: 'BA',
  Brazil: 'BR',
  Canada: 'CA',
  CAN: 'CA',
  'Cape Verde': 'CV',
  Colombia: 'CO',
  Croatia: 'HR',
  CRO: 'HR',
  'Curaçao': 'CW',
  CUW: 'CW',
  'Czech Republic': 'CZ',
  'DR Congo': 'CD',
  Ecuador: 'EC',
  ECU: 'EC',
  Egypt: 'EG',
  EGV: 'EG',
  England: 'gb-eng',
  ENG: 'gb-eng',
  France: 'FR',
  FRA: 'FR',
  Germany: 'DE',
  GER: 'DE',
  Ghana: 'GH',
  GHA: 'GH',
  Haiti: 'HT',
  Iran: 'IR',
  IRN: 'IR',
  Iraq: 'IQ',
  IRQ: 'IQ',
  'Ivory Coast': 'CI',
  CIV: 'CI',
  Japan: 'JP',
  Jordan: 'JO',
  Mexico: 'MX',
  Morocco: 'MA',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  Norway: 'NO',
  NOR: 'NO',
  Panama: 'PA',
  PAN: 'PA',
  Paraguay: 'PY',
  Portugal: 'PT',
  Qatar: 'QA',
  QAT: 'QA',
  'Saudi Arabia': 'SA',
  Scotland: 'gb-sct',
  Senegal: 'SN',
  SEN: 'SN',
  'South Africa': 'ZA',
  'South Korea': 'KR',
  Spain: 'ES',
  Sweden: 'SE',
  Switzerland: 'CH',
  SUI: 'CH',
  Tunisia: 'TN',
  Turkey: 'TR',
  USA: 'US',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
};

/** Subdivision flags not in country-flag-icons — served via flagcdn */
const SUBDIVISION_CODES = new Set(['gb-eng', 'gb-sct']);

export function getTeamCountryCode(team: string): string | null {
  return TEAM_COUNTRY_CODE[team] ?? null;
}

export function isSubdivisionFlag(code: string) {
  return SUBDIVISION_CODES.has(code.toLowerCase());
}
