/** FIFA team name → ISO 3166-1 alpha-2 (or subdivision slug for flagcdn) */
const TEAM_COUNTRY_CODE: Record<string, string> = {
  Algeria: 'DZ',
  Argentina: 'AR',
  Australia: 'AU',
  AUS: 'AU',
  Austria: 'AT',
  Belgium: 'BE',
  BEL: 'BE',
  'Bosnia & Herzegovina': 'BA',
  BIH: 'BA',
  Brazil: 'BR',
  Canada: 'CA',
  CAN: 'CA',
  'Cape Verde': 'CV',
  Colombia: 'CO',
  Croatia: 'HR',
  CRO: 'HR',
  'Curaçao': 'CW',
  CUW: 'CW',
  'Czech Republic': 'CZ',
  'DR Congo': 'CD',
  Ecuador: 'EC',
  ECU: 'EC',
  Egypt: 'EG',
  EGV: 'EG',
  England: 'gb-eng',
  ENG: 'gb-eng',
  France: 'FR',
  FRA: 'FR',
  Germany: 'DE',
  GER: 'DE',
  Ghana: 'GH',
  GHA: 'GH',
  Haiti: 'HT',
  Iran: 'IR',
  IRN: 'IR',
  Iraq: 'IQ',
  IRQ: 'IQ',
  'Ivory Coast': 'CI',
  CIV: 'CI',
  Japan: 'JP',
  Jordan: 'JO',
  Mexico: 'MX',
  Morocco: 'MA',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  Norway: 'NO',
  NOR: 'NO',
  Panama: 'PA',
  PAN: 'PA',
  Paraguay: 'PY',
  Portugal: 'PT',
  Qatar: 'QA',
  QAT: 'QA',
  'Saudi Arabia': 'SA',
  Scotland: 'gb-sct',
  Senegal: 'SN',
  SEN: 'SN',
  'South Africa': 'ZA',
  'South Korea': 'KR',
  Spain: 'ES',
  Sweden: 'SE',
  Switzerland: 'CH',
  SUI: 'CH',
  Tunisia: 'TN',
  Turkey: 'TR',
  USA: 'US',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
};

/** Subdivision flags not in country-flag-icons — served via flagcdn */
const SUBDIVISION_CODES = new Set(['gb-eng', 'gb-sct']);

export function getTeamCountryCode(team: string): string | null {
  return TEAM_COUNTRY_CODE[team] ?? null;
}

export function isSubdivisionFlag(code: string) {
  return SUBDIVISION_CODES.has(code.toLowerCase());
}

export const TEAM_NAMES: Record<string, { en: string; zh: string }> = {
  BEL: { en: 'BELGIUM', zh: '比利时' },
  EGV: { en: 'EGYPT', zh: '埃及' },
  FRA: { en: 'FRANCE', zh: '法国' },
  SEN: { en: 'SENEGAL', zh: '塞内加尔' },
  ENG: { en: 'ENGLAND', zh: '英格兰' },
  CRO: { en: 'CROATIA', zh: '克罗地亚' },
  SUI: { en: 'SWITZERLAND', zh: '瑞士' },
  BIH: { en: 'BOSNIA & HERZEGOVINA', zh: '波黑' },
  USA: { en: 'USA', zh: '美国' },
  AUS: { en: 'AUSTRALIA', zh: '澳大利亚' },
  GER: { en: 'GERMANY', zh: '德国' },
  CIV: { en: 'IVORY COAST', zh: '科特迪瓦' },
  IRN: { en: 'IRAN', zh: '伊朗' },
  IRQ: { en: 'IRAQ', zh: '伊拉克' },
  GHA: { en: 'GHANA', zh: '加纳' },
  CAN: { en: 'CANADA', zh: '加拿大' },
  QAT: { en: 'QATAR', zh: '卡塔尔' },
  ECU: { en: 'ECUADOR', zh: '厄瓜多尔' },
  CUW: { en: 'CURAÇAO', zh: '库拉索' },
  NOR: { en: 'NORWAY', zh: '挪威' },
  PAN: { en: 'PANAMA', zh: '巴拿马' },
};
